# Generated by Django 2.2.4 on 2021-01-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='visits',
            field=models.ManyToManyField(related_name='visited_parks', to='main_app.User'),
        ),
    ]
