# Generated by Django 2.2.4 on 2021-01-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_park_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='img_url2',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
        migrations.AddField(
            model_name='park',
            name='img_url3',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
