# Generated by Django 2.2.4 on 2021-01-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210128_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='img_url2',
            field=models.CharField(default='nps.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='park',
            name='img_url3',
            field=models.CharField(default='nps.png', max_length=255),
        ),
    ]
