# Generated by Django 2.2.4 on 2021-01-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210128_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='img1_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='img2_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='img3_desc',
            field=models.TextField(null=True),
        ),
    ]
